Add a repeatable flag to Section
hmpf/easydmp pull request #172
Opened 2020-11-24 08:36 UTC by vbhavdal

Is this a sensible first step?

2020-11-24 14:23 UTC, hmpf commented
> Is this a sensible first step?

Absolutely. When that one is in we can argue about where to store answers of repeated sections :)

2020-11-25 12:33 UTC, hmpf requested changes

2020-11-25 12:33 UTC, hmpf commented on src/easydmp/dmpt/migrations/0012_section_repeatable.py
> +        ('dmpt', '0011_section_optional'),
This'll go after the squashed migrations so this line will have to be updated.

2020-11-25 12:34 UTC, closed without merging

2020-11-25 12:34 UTC, vbhavdal commented
Redo after squash